[package]
name = "app"
version = "0.0.1"
description = "A Tauri App"
authors = ["Francesc Arpí Roca"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5.2", features = [] }
rust-ini = "0.20.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
chrono = "0.4.31"
oxhttp = { version = "0.1.7", features = ["native-tls"] }
platform-dirs = "0.3.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
