name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          sudo apt-get install libgtk-3-dev

      - name: Run tests
        run: |
          cd src-tauri
          cargo test
